Update de.locallang.xlf
TYPO3-Solr/ext-solr pull request #2896
Opened 2021-03-15 11:37 UTC by mck

Submit is an action so the right wording would be "suchen"

# What this pr does

Change the translation for the "submit" action label

2021-03-22 11:38 UTC, dkd-kaehm reviewed
Thanks for your contributions.
I can't currently confirm the change and want at least the confirmation from somebody else.

You can currently use the TYPO3s way to override the translation labels you want to change.
Please refer to the docs or see following example: 

https://github.com/TYPO3-Solr/ext-solrfluidexample/blob/master/ext_localconf.php#L6

2021-03-22 11:46 UTC, dkd-kaehm commented
@dkd-friedrich 
Please confirm or close the change.
By confirmation we need Backports onto release-10.0.x and release-11.0.x.
Please consider the compatibility to #2875

2021-03-24 13:14 UTC, dkd-friedrich commented
Sounds reasonable to me, but I would suggest to start with capital letter 
`suchen` => `Suchen`

Our other labels for buttons and links always start with a capital letter and we should keep it that way here as well

2021-03-24 13:15 UTC, dkd-friedrich requested changes

2021-03-24 13:15 UTC, dkd-friedrich commented on Resources/Private/Language/de.locallang.xlf
> +				<target>suchen</target>
I would suggest to start with a capital letter, similiar to the other labels

2021-07-17 07:25 UTC, dkd-kaehm commented
Is part of #2875

2021-07-17 07:25 UTC, closed without merging