[BUGFIX] Respect TCA setting of 'tstamp' field
TYPO3-Solr/ext-solr pull request #3038
Opened 2021-09-27 11:23 UTC by jschlier

# What this pr does
When updating a tracked, localisable item in the Solr queue the TCA setting for the "tstamp" / last updated on field ist not evaluated.
This leads to an exception with records that use a non-default name for this database field.

This PR changes this behaviour to use the TCA settings for the `$itemType`.

# How to test
Add (or change) a custom record that is configured for Solr to use a non-default name for this field. E.g:
```php
$GLOBALS['TCA'][$table]['ctrl']['tstamp'] = 'updated_on';
```
Then you can test this exception and the fix before and after applying this small change.

Fixes: TYPO3-Solr#3037

2021-09-27 12:48 UTC, dkd-friedrich requested changes
Thanks for the adjustment, sounds reasonable to me in general.

In the PR, however, 2 different variables were used by mistake, `$timeStampField` and `$tStampField`. Please check.

2021-09-27 12:53 UTC, jschlier commented
Oh. My bad - I quickly fixed this typo.

2021-09-28 06:59 UTC, dkd-kaehm commented
We want the ports into release-11.1.x and release-11.0.x

2021-09-29 12:34 UTC, dkd-friedrich approved these changes
Thx! LGTM

2021-09-29 12:36 UTC, dkd-friedrich commented
> We want the ports into release-11.1.x and release-11.0.x

I've prepared the backports

- #3039
- #3040

2021-09-29 12:37 UTC, merged