[BUGFIX] Avoid 404 handler deadlock in special case
TYPO3-Solr/ext-solr pull request #3275
Opened 2022-07-04 08:50 UTC by saitho

# What this pr does

The error occurs in a special case when:
- there is no "page" object in TypoScript
- a 404 handler is configured in site configuration
- there is a language without translated root page

In this case, the 404 handler will be stuck in a deadlock, increasing
the RAM usage until it uses all of the available RAM.

This deadlock happens, when the tsfeCache is null. Therefore we ensure
TSFE is set in cache when internal server errors occurred.

# How to test

See #3274. With this fix, the error should not happen anymore.

Fixes: #3274

2022-07-15 05:22 UTC, dkd-kaehm requested changes
Hey @saitho,
could you please check if following change instead of your patch will fix your troubles?

https://github.com/TYPO3-Solr/ext-solr/blob/3ea33b4f8387f77d4a34670d0aa7bf02bdf57054/Classes/FrontendEnvironment/Tsfe.php#L130

to

`if (!array_key_exists($cacheIdentifier, $this->tsfeCache)) { `

It seems to be wrong condition for checking the cache hits on nullable values....

2022-07-15 09:26 UTC, saitho commented
> Hey @saitho, could you please check if following change instead of your patch will fix your troubles?

@dkd-kaehm Nope, did not work :(

2022-09-13 09:50 UTC, dkd-kaehm commented
For instance, the fix was done in CORE See: https://github.com/typo3/typo3/commit/fc51ccbf2b.
We want to test if that fix working on EXT:solr.

2022-09-23 11:35 UTC, dkd-kaehm commented
@saitho could you please check if the error is gone with TYPO3 https://github.com/TYPO3/typo3/commit/fc51ccbf2b + ?

2022-10-06 13:06 UTC, saitho commented
Can't confirm this issue with the latest TYPO3 version.

2022-10-06 13:06 UTC, closed without merging