[BUGFIX] Custom doktype is deleted from solr after saving with custom…
TYPO3-Solr/ext-solr pull request #3451
Opened 2023-01-11 16:05 UTC by b3nkai

# What this pr does

When a page is saved, the GarbageHandler will check in all queue configuration if the doktype is allowed, not only in "pages" queue configuration.

# How to test

1. Create a custom page type, 100 / news for example
2. Include default solr configuration
3. Add this custom configuration
plugin.tx_solr.index.queue {
pages.allowedPageTypes = 1
pages.additionalWhereClause = doktype IN(1) AND no_search = 0
news < .pages
news.allowedPageTypes = 100
news.additionalWhereClause = doktype IN(100) AND no_search = 0
}
4. Create a new page with the custom type 100
5. Start indexing and checks the page is right in solr
6. Update the page by changing its title
7. Check in solr, the page is still there

Fixes: #3450

2023-01-19 22:55 UTC, dkd-kaehm requested changes
Thanks for fixing that issue.
There are some review issues, which must be solved.
I'll push the change soon.

2023-01-19 22:55 UTC, dkd-kaehm commented on Classes/System/Configuration/TypoScriptConfiguration.php
> +        }
Is maybe the condition member for checking if the queue/type is enabled?
Also for example for pages = 1|0 setting: 

https://github.com/TYPO3-Solr/ext-solr/blob/cb5b5284a7cb55490e36477b0e4b3f3e59145616/Configuration/TypoScript/Solr/setup.typoscript#L24-L31

```suggestion
        foreach ($configuration as $queueName => $queueConfiguration) {
            if (is_array($queueConfiguration)
                && !empty($queueConfiguration['allowedPageTypes'])
                && $this->getIndexQueueConfigurationIsEnabled(rtrim($queueName,'.'))
            ) {
                $allowedPageTypes = array_merge($allowedPageTypes, GeneralUtility::trimExplode(',', $queueConfiguration['allowedPageTypes'], true));
            }
        }
```

2023-01-20 10:21 UTC, dkd-kaehm approved these changes

2023-01-23 14:15 UTC, dkd-friedrich approved these changes
LGTM

2023-01-23 14:19 UTC, dkd-friedrich commented
I'll provide a backport for 11.5

2023-01-23 14:19 UTC, merged