[FEATURE] Add arm64-platform support (e.g. for Apple Silicon processors) to docker-image
TYPO3-Solr/ext-solr pull request #3501
Opened 2023-02-19 19:30 UTC by sjorek

# What this PR does

This PR adds arm64-platform support (e.g. for Apple Silicon processors) to `typo3solr/ext-solr` docker-image. Therefore several changes were neccessary:

- Update all required github-actions in .github/workflow/ci.yml
- Add a new `publish-docker-hub` job to the pipeline
  - Reuse the cached `typo3solr/ext-solr` image artifact from the `test`-job for `linux/amd64` (Intel & Co.) platforms
  - Build `typo3solr/ext-solr` image with the additional `linux/arm64` (Apple Silicon) platform
  - I tried my best to guess which (kind of) git-tag and -branch corresponds the which docker-image tag in your current docker-hub build setup
    - The current git-tag/-branch to docker-image tag mapping is:
      ```markdown
      | git-branch or -tag | docker image-tag(s) |
      |--------------------|---------------------|
      | main               | latest              |
      | release-11.5.x     | release-11.5.x      |
      | 11.5.1             | 11.5.1, 11.5, 11    |(†)
      | 11.2.1             | 11.2.1, 11.2        |(†)
      | 10.0.1             | 10.0.1, 10.0, 10    |(†)
      | 11.5.0-rc-1        | 11.5.x-dev          |
      ```
      **(†)** git-tags without pre-release suffix produce three docker image-tags, if they represent latest release of its MAJOR version, otherwise they produce only two docker-image tags.
- Rename the `publish`-job to `publish-typo3-ter`, to avoid confusion, with the new `publish-docker-hub` job.

# New GitHub Action environment-variables and secrets

- two new secrets are needed:
  ```yaml
  DOCKERHUB_USERNAME : "typo3solr"
  DOCKERHUB_TOKEN    : "DOCKERHUB_PERSONAL_ACCESS_TOKEN"
  ```
- three new environment-variables
  ```yaml
  DOCKER_PLATFORMS  :  "linux/amd64,linux/arm64"
  DOCKER_IMAGE_NAME : "${{ secrets.DOCKERHUB_USERNAME }}/ext-solr"
  # This one is overridden automatically, based upon branch or tag, see above
  DOCKER_IMAGE_TAGS : ""
  ```

# How to test

Good question? I tried to test it with https://github.com/nektos/act#readme on Apple Silicon M2 Max and Mac OS Ventura 13.2.1. This brought me surprisingly far, but in the end I had no luck, as the `cibuild_docker.sh` always fails in the `assertDataPathIsCreatedByApacheSolr` function. This is still confusing to me, as this does not seem to be related with this PR at all.

Hope we can finish this (or another) solution together?

Cheers,
Stephan

------------------

As soon as everything ist running, this PR …
Fixes: #2891

2023-02-20 10:40 UTC, dkd-kaehm commented
@sjorek 
Wow,
Thanks for kick-starting that PR.
We'll proceed with it in TYPO3 12 compatibility task.

2023-02-20 15:33 UTC, brandung-sjorek requested changes

2023-02-20 15:33 UTC, brandung-sjorek commented on .github/workflows/ci.yml
> +          platforms: ${{ env.DOCKER_IMAGE_TAGS }}
Here is a tiny glitch - should be `${{ env.DOCKER_PLATFORMS }}` - i'll fix it ASAP.

2023-02-24 18:50 UTC, dkd-kaehm approved these changes
@sjorek @brandung-sjorek 
Thanks for your work, it looks really good. 
@dkd-friedrich approved the patch as well.

We must make test on docker hub by some test account to avoid any troubles with current builds and setup of automated builds on Docker hub.
I'm currently a fully involved on TYPO3 12 compatibility task, 
therefore we'll look and test it a little bit later.

2023-02-25 11:50 UTC, sjorek commented
@dkd-kaehm Good news, I'll keep my fingers crossed, while I'm still trying to pass the `cibuild_docker.sh` tests in the local `act` run. All tests except `assertDataPathIsCreatedByApacheSolr` are passing - which means solr is per se working. There is something strange going on with the local volume - I bet it's either the way `act` works or something with the multiarch support, when running `act` on Apple Silicon.

Let me know if I can be of any help.

2025-05-09 15:37 UTC, dkd-kaehm commented
@sjorek 
Thanks for your cotribution. I inspired by this pull-request and replaced it by #4359.
Soonish the ARM64/ppc64le/AMD64 dev state images online and after releases the stable as well.

2025-05-09 15:37 UTC, closed without merging