[FEATURE] Make statistics more dynamic
TYPO3-Solr/ext-solr pull request #3548
Opened 2023-03-19 11:20 UTC by ayacoo

# What this pr does

The statistics are hard-coded so far. It is now defined in Typoscript. If no values are defined, the previous values are set as the default value in the code to prevent a breaking change.

# How to test

Simply add TypoScript and look at the statistics in the backend info module.

# Hint

The documentation is adapted if everything fits in terms of content and the variable naming is also good enough.

Fixes: #3534

2023-03-31 11:44 UTC, bmack commented
How about pageTsConfig instead?

2023-04-05 18:26 UTC, ayacoo commented
Would certainly be more elegant but would then also open up another place where you can configure. Therefore I would rather stay with the TypoScript.

2023-04-12 12:56 UTC, dkd-kaehm requested changes
The docs part is missing.

2023-04-12 17:50 UTC, ayacoo commented
@dkd-kaehm I will gladly add the documentation if I get the OK for variable naming and location ;-)

2023-04-24 11:27 UTC, dkd-kaehm commented
> @dkd-kaehm I will gladly add the documentation if I get the OK for variable naming and location ;-)

If you mean following names, they are fine ;):

```
statistics = 1
  statistics {
    anonymizeIP = 1
    topHits {
      days = 30
      limit = 5
    }
    noHits {
      days = 30
      limit = 5
    }
    queries {
      days = 30
      limit = 100
    }
  }
```

2023-05-02 08:02 UTC, dkd-kaehm approved these changes
Thanks for your work.
We'll proceed with the merge.

Todo Maintainers: 
- [ ] merge suggestions
- [ ] **use squash button for merging!**

2023-05-02 08:06 UTC, merged