Migrate ext solrfluidgrouping
TYPO3-Solr/ext-solr pull request #3656
Opened 2023-06-01 13:35 UTC by sfroemkenjw

# What this pr does

Migrate EXT:solrfluidgrouping into EXT:solr

2023-06-02 09:42 UTC, bmack approved these changes
LGTM

2023-06-02 13:34 UTC, dkd-friedrich commented
I've pushed some adjustments and bugfixes, but there is still an issue with "allowGetParameterSwitch" and parameter `tx_solr[grouping]`, grouping cannot be disabled as intended. I'll analyze this next week

2023-06-05 14:54 UTC, dkd-kaehm requested changes
We want rebase against main.
To many changes overlapped with movements to PSRs

2023-06-05 14:54 UTC, dkd-kaehm commented on Classes/Query/Modifier/Grouping.php
> +class Grouping implements Modifier, SearchRequestAware
Whhoops, already overlapped:

See: https://github.com/TYPO3-Solr/ext-solr/blob/092e2a729471607b2b23a7519d2ebdeb14f579b3/Documentation/Releases/solr-release-12-0.rst?plain=1#L35

2023-06-06 09:05 UTC, bmack approved these changes

2023-06-06 09:05 UTC, bmack approved these changes

2023-06-07 11:55 UTC, merged