[FEATURE] Allow using complex filter values in FlexForm
TYPO3-Solr/ext-solr pull request #3703
Opened 2023-06-21 10:51 UTC by echavaillaz

With this PR it is now possible to use complex query in FlexForm filter value.

Fixes: #2151

2023-06-21 12:28 UTC, dkd-kaehm requested changes
The code base LGTM!
Please add 
* the hints from your issue comment https://github.com/TYPO3-Solr/ext-solr/issues/2151#issuecomment-1600623995
to the docs, so users are aware of.
* and a little sentence in Documentation/Releases/solr-release-12-0.rst about this feature.

2023-06-22 08:08 UTC, dkd-kaehm commented
@echavaillaz 
Please fix the issues from GH-actions:
https://github.com/TYPO3-Solr/ext-solr/actions/runs/5334225100/jobs/9668256731?pr=3703

For CS fixes just run this command:
`TYPO3_VERSION=12.4.x-dev composer tests:setup && composer t3:standards:fix`

The unit test and/or method `ConfigurationService::getFilterFromFlexForm()` must be adjusted:
```
1) ApacheSolrForTypo3\Solr\Tests\Unit\System\Service\ConfigurationServiceTest::canOverrideConfigurationWithFlexFormSettings with data set "simpleInteger" ('id', 4711, 'id:4711')
TypeError: ApacheSolrForTypo3\Solr\Tests\Unit\System\Service\ConfigurationServiceTest::canOverrideConfigurationWithFlexFormSettings(): Argument #2 ($filterValue) must be of type string, int given, called in /home/runner/work/ext-solr/ext-solr/.Build/vendor/phpunit/phpunit/src/Framework/TestCase.php on line 1608

/home/runner/work/ext-solr/ext-solr/Tests/Unit/System/Service/ConfigurationServiceTest.php:107
/home/runner/work/ext-solr/ext-solr/.Build/bin/phpunit:123

--

There was 1 failure:

1) ApacheSolrForTypo3\Solr\Tests\Unit\System\Service\ConfigurationServiceTest::canOverrideConfigurationWithFlexFormSettings with data set "escapedString" ('id', 'foo"bar', 'id:"foo\"bar"')
Failed asserting that two arrays are equal.
--- Expected
+++ Actual
@@ @@
 Array (
-    0 => 'id:"foo\"bar"'
+    0 => 'id:foo"bar'
 )
```

2023-06-30 08:39 UTC, echavaillaz commented
Ready to test?

2023-10-12 16:34 UTC, dkd-kaehm approved these changes

2023-10-12 20:32 UTC, merged