[BUGFIX] Make BeforeSearchResultIsShownEvent more usable
TYPO3-Solr/ext-solr pull request #3704
Opened 2023-06-21 11:45 UTC by georgringer

It would be cool if properties of the event could be changed. Otherwise the event doesn't help much - IMO

I need it e.g. for the pagination to be changed

2023-06-21 12:16 UTC, dkd-kaehm commented on Classes/Event/Search/BeforeSearchResultIsShownEvent.php
> +    protected function setPagination(PaginationInterface $pagination): void
Why not public?

2023-06-21 12:21 UTC, dkd-kaehm requested changes
Thanks for this patch.
There are most probably two changes required.

2023-06-21 12:21 UTC, dkd-kaehm commented on Classes/Event/Search/BeforeSearchResultIsShownEvent.php
>  use ApacheSolrForTypo3\Solr\Pagination\ResultsPagination;
This line should is not needed anymore.

2023-06-22 08:17 UTC, dkd-kaehm approved these changes
LGTM!
The PR can be squashed and merged.

2023-06-22 08:23 UTC, georgringer commented
@dkd-kaehm I don't know if other properties should be setable as well but certainly all other events must be changed as well to be usable for extension authors. I suggest to use a different PR for that

2023-06-26 06:11 UTC, georgringer commented
@dkd-kaehm wanna merge that?

2023-06-26 07:33 UTC, bmack commented
Can we add them to the other Events that are related to Actions/Controllers?

2023-06-26 07:38 UTC, merged