[TASK] Full fixed french translation
TYPO3-Solr/ext-solr pull request #3996
Opened 2024-04-05 10:01 UTC by dkd-kaehm

Fixes: #3983
Ports: #3984 

@megamisan please review this port

2024-05-07 13:38 UTC, dkd-kaehm commented
@megamisan Applied your patch file over my commit.
Please check it again.

2024-05-08 19:50 UTC, megamisan requested changes
Everything else looks good to me.

2024-05-08 19:50 UTC, megamisan commented on Resources/Private/Language/fr.locallang.xlf
> +				<target>La file l&apos;indexation gère l&apos;indexation du contenu. Le contenu entre dans la file d&apos;indexation par l&apos;initialisation ci-dessous ou lors de la création d&apos;un nouveau
Here, I had a typo in my first commit.

```suggestion
				<target>La file d&apos;indexation gère l&apos;indexation du contenu. Le contenu entre dans la file d&apos;indexation par l&apos;initialisation ci-dessous ou lors de la création d&apos;un nouveau contenu selon la configuration. Les éléments de la file d&apos;indexation sont indexés en commençant par les changements les plus récents jusqu&apos;à ce que tous les éléments de la file d&apos;indexation aient été indexés.</target>
```

2024-05-08 19:50 UTC, megamisan commented on Resources/Private/Language/fr.locallang.xlf
> +				<target>File d&apos;&apos;indexation</target>
Another one here.

```suggestion
				<target>File d&apos;indexation</target>
```

2024-05-13 06:20 UTC, merged