Release 3.1.x
TYPO3-Solr/ext-solr pull request #924
Opened 2017-01-27 16:15 UTC by tgriessbach

[FEATURE] allow to toggle index clearing in ReIndexTask

* adds a checkbox to ReIndexTask
* calls cleanUpIndex() only if checked 

This allows to periodically reset the IndexQueue without killing the while Search Index.

2017-01-27 19:21 UTC, irnnr requested changes

2017-01-27 19:21 UTC, irnnr commented on Classes/Task/ReIndexTaskAdditionalFieldProvider.php
> +            'label' => 'Clear Index for selected sites and record types',
Can you move this to a localizable label please?

2017-01-27 19:21 UTC, irnnr commented on Classes/Task/ReIndexTask.php
> +    protected $clearSearchIndex;
I'd suggest a default value of `false` just to make sure existing tasks are ok when they get deserialized after an update to a version containing this code.

2017-01-30 13:54 UTC, aWuttig reviewed
I think its better to use array(), because EXT:solr maybe support PHP 5.3 applications and this syntax is only supported since 5.4

http://php.net/manual/de/migration54.new-features.php

2017-01-30 13:54 UTC, tgriessbach commented
Thanks for the feedback, I changed it according to your suggestions.

2017-01-30 22:39 UTC, irnnr commented
@tgriessbach just noticed; if you want this to go into the 3.1 branch you need to make a PR for master first (and the release branches in between). Also, like @aWuttig already mentioned, since the 3.1 branch supports TYPO3 v6LTS, you need to use the old array syntax (does not apply for master).

2017-01-30 22:40 UTC, irnnr requested changes

2017-01-30 22:40 UTC, irnnr commented on Classes/Task/ReIndexTask.php
> +    protected $indexingConfigurationsToReIndex = [];
Can't use short array syntax for the 3.1 release branch.

2026-05-01 09:40 UTC, closed without merging